### PR TITLE
pt translation

### PR DESCRIPTION
**Pull request by psenough**
also added:
- inkscape version requirements on readme
- alphabetical sorting of the languages

### CODE REVIEW

**Comment by lunasorcery** [comment]
I think I'd prefer to keep English at the top of the list, and I'm not completely sure yet how I want to handle ordering the others (esp. when we add Japanese - how should 日本語 sort?)

For now, could you put English back at the top, with the others alphabetical?

Good catch on the Inkscape version - I think I would've preferred a private message about that rather than lumping it in with an unrelated change set, but I'll let it slide this time.

**Comment by lunasorcery** [comment]
Also - which alphabet sorts Português before Nederlands? 😛

**Comment by psenough** [comment]
the alphabet of people still under the weather with gastroentritis clearly :D i'll do a commit without the alphabetical sorting then.

**Comment by lunasorcery** [comment]
gah, accepted bitnenfer's spanish translation and now I can't automerge because of conflicts in list.json - could you take care of it and then I'll get yours merged in?

**Comment by psenough** [comment]
conflicts resolved

**Comment by lunasorcery** [comment]
Thanks!

**Pull request merged**
